version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python --version
#      - run: pip install -r requirements.txt
#      - run: pip install -r requirements-test.txt
