version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: make install_requirements
      - run: python --version
      - run: make test
