version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: make install_requirements
      - run: python --version

  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: make install_requirements
      - run: python --version
      - run: make test-coverage
