version: 2.1

workflows:
  test_deploy_package:
    jobs:
      - test
      - package:
          requires:
            - test
          filters:
            tags:
              only: /.*/

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: make install_requirements
      - run: python --version
#      - run: make test
      - run: make test-coverage
#      - run: tox -e pytest

  package:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: make build
      - run: make upload