version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          filters:
            tags:
              only: /^v.*/

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
#      - run: make install_requirements
      - run: python --version
      - run: make test-coverage

  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
#      - run: make install_requirements
      - run: python --version
