#version: 2.1
#
#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - test
#      - build:
#          requires:
#            - test
#          filters:
#            tags:
#              only: /^v.*/
#
#jobs:
#  test:
#    docker:
#      - image: cimg/python:3.9
#    steps:
#      - checkout
#      - run: make install_requirements
#      - run: python --version
#      - run: make test-coverage
#      # The following step will only run if the tests pass
#      - run: |
#          if [[ $(make test-coverage) == "PASS" ]]; then
#            echo "Tests passed, building"
#          fi
#
#  build:
#    docker:
#      - image: cimg/python:3.9
#    steps:
#      - checkout
#      - run: make install_requirements
#      - run: python --version
#      # The following step will only run if the tests pass and the tag is pushed
#      - run: |
#          if [[ $(make test-coverage) == "PASS" ]]; then
#            echo "Tests passed and tag pushed, building"
#          fi
