name: Python Package CI/CD

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
    tags:
        - "v*.*.*"
  pull_request:
    types:
      - closed
    branches:
      - master
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make install_requirements

      - name: flake8
        run: flake8

      - name: Run tests
        run: make test-coverage

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make install_requirements

      - name: Build and deploy package
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/* --verbose
